version: '3.9'

services:
  db:
    image: postgres
    container_name: postgres_test
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_DB_TEST=${DB_NAME_TEST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - database_network

  backend:
    build: ./server
    container_name: backend_test
    command: npm test
    environment:
      NODE_ENV: test

      DB_NAME_TEST: ${DB_NAME_TEST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - database_network

networks:
  database_network:
    driver: bridge
